spring:
  application:
    name: web-crawler

logging.level.com.bot.crawler: DEBUG

### Custom Properties ###
crawler:
  external-links-capture:
    enable: false
  depth-based-scan:
    enable: true
  source-connect-timeout: 5 # connect timeout in seconds